services:
  mongo:
    image: mongo:6.0
    container_name: erp-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: erpdb
    volumes:
      - mongo-data:/data/db
    networks:
      - erp-network

  backend:
    build: ./backend
    container_name: erp-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    networks:
      - erp-network
    volumes:
      - ./backend/src:/usr/src/app/src
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    container_name: erp-frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - erp-network

  nginx:
    build: ./frontend
    container_name: erp-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - erp-network

volumes:
  mongo-data:
    driver: local

networks:
  erp-network:
    driver: bridge
